[package]
name = "phantom"
version = "0.1.0"
authors = ["Rafael Villegas <rafa.villegas.michel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.3.2"